#!/bin/bash
APP_NAME := "app"

set dotenv-required := true
set dotenv-load := true
set dotenv-path := "./.env"
set export :=true

default:
    just --list

start:
    docker compose up -d  && just logs

stop:
    docker compose down

kill:
    docker compose down -v

restart:
    docker compose down
    docker compose up
    just logs {{APP_NAME}}

[doc("see the application log")]
logs:
    docker compose logs -f {{APP_NAME}}
