ktor:
    application:
        modules:
            - com.axe.ApplicationKt.module
    deployment:
        port: 5000
postgres:
  url: "jdbc:postgresql://localhost/default"
  user: username
  password: password